name: freeroot
version: '1.5-SNAPSHOT'
main: org.freeroot
api-version: '1.21'
description: freeroot =0
website: https://github.com/Mytai20100/freeroot-jar

commands:
  root:
    description: Execute shell commands
    usage: /<command> [args]
    aliases: [r, rt]
  neofetch:
    description: Run neofetch system info
    usage: /<command>
  info:
    description: Display system information
    usage: /<command>